version: '3.8'
services:
  dust3r-demo:
    build:
      context: ./files
      dockerfile: cpu.Dockerfile 
    ports:
      - "7860:7860"
    volumes:
      - ./files/checkpoints:/dust3r/checkpoints
    environment:
      - DEVICE=cpu
      - MODEL=${MODEL:-DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth}
    cap_add:
      - IPC_LOCK
      - SYS_RESOURCE
